alenkura/accounts/urls.py
from django.urls import path
from .views import login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

alenkura/alenkura/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('core/', include('core.urls')),
    path('ped/', include('ped.urls')),
    path('paci/', include('paciApp.urls')),
    path('instrumentos/', include('instrumentosApp.urls')),
    path('aula/', include('aula.urls')),
]

alenkura/aula/urls.py
from django.urls import path

from .views import proyecto_delete, proyecto_download, proyecto_pdf, proyecto_view

app_name = "aula"

urlpatterns = [
    path("proyecto/", proyecto_view, name="proyecto_form"),
    path("proyecto/<int:pk>/descargar/", proyecto_download, name="proyecto_download"),
    path("proyecto/<int:pk>/pdf/", proyecto_pdf, name="proyecto_pdf"),
    path("proyecto/<int:pk>/eliminar/", proyecto_delete, name="proyecto_delete"),
]

alenkura/core/urls.py
from django.urls import path
from .views import estudiantes_view, gestion_view, index, send_email

app_name = 'coreApp'

urlpatterns = [
    path('', index, name='index'),
    path('estudiantes', estudiantes_view, name='estudiantes'),
    path('gestion', gestion_view, name='gestion'),
    path('correo/<int:id>', send_email, name='send_mail')
]

alenkura/ped/urls.py
from django.urls import path

from . import views

app_name = "ped"

urlpatterns = [
    path("formulario/", views.formulario_view, name="formulario"),
    path("plan/<int:plan_id>/pdf/", views.plan_pdf_view, name="plan_pdf"),
    path("plan/<int:plan_id>/eliminar/", views.plan_delete_view, name="plan_eliminar"),
]

alenkura/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap');

    body {
      font-family: 'Red Hat Display', sans-serif;
    }
  </style>

</head>

<body class="min-h-screen dark:bg-gray-800 dark:text-gray-100">
  <div class="flex min-h-screen">
    <aside class="flex flex-col w-64 dark:bg-gray-900 p-4 justify-between shadow-xl border-r border-gray-400 dark:border-gray-600">
      <ul class="space-y-1">
        <p class="text-xl text-center mb-4">Bienvenida/o, {{user.username}}</p>
        <li>
          <a href="{% url 'coreApp:index' %}"
            class="flex items-center gap-2 rounded-lg bg-gray-100 px-4 py-2 text-gray-700 dark:bg-gray-800 dark:hover:bg-teal-900 dark:text-gray-200">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
            </svg>

            <span class="text-sm font-medium"> General </span>
          </a>
        </li>

        <li>
          <details class="group [&amp;_summary::-webkit-details-marker]:hidden">
            <summary
              class="group flex items-center justify-between rounded-lg px-4 py-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200">
              <div class="flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 0 0 3.741-.479 3 3 0 0 0-4.682-2.72m.94 3.198.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0 1 12 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 0 1 6 18.719m12 0a5.971 5.971 0 0 0-.941-3.197m0 0A5.995 5.995 0 0 0 12 12.75a5.995 5.995 0 0 0-5.058 2.772m0 0a3 3 0 0 0-4.681 2.72 8.986 8.986 0 0 0 3.74.477m.94-3.197a5.971 5.971 0 0 0-.94 3.197M15 6.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm6 3a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Zm-13.5 0a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Z" />
                </svg>


                <span class="text-sm font-medium"> Curso </span>
              </div>

              <span class="shrink-0 transition duration-300 group-open:-rotate-180">
                <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd"
                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                    clip-rule="evenodd"></path>
                </svg>
              </span>
            </summary>

            <ul class="mt-2 space-y-1 px-4">

              <li>
                <a href="{% url 'coreApp:gestion' %}"
                  class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200">
                  Gestión académica
                </a>
              </li>

              <li>
                <a href="{% url 'coreApp:estudiantes' %}"
                  class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200">
                  Estudiantes
                </a>
              </li>

              <li>
                <a href="{% url 'ped:formulario' %}"
                  class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200">
                  Plan de Evaluación Diagnóstica
                </a>
              </li>

              <li>
                <a href="{% url 'aula:proyecto_form' %}"
                  class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200">
                  Proyecto de aula
                </a>
              </li>

            </ul>
          </details>
        </li>

        <li>
          <details class="group [&amp;_summary::-webkit-details-marker]:hidden">
            <summary
              class="group flex items-center justify-between rounded-lg px-4 py-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200">
              <div class="flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                </svg>


                <span class="text-sm font-medium"> Cuenta </span>
              </div>

              <span class="shrink-0 transition duration-300 group-open:-rotate-180">
                <svg xmlns="http://www.w3.org/2000/svg" class="size-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd"
                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                    clip-rule="evenodd"></path>
                </svg>
              </span>
            </summary>

            <ul class="mt-2 space-y-1 px-4">

              <li>
                <form action="{% url 'accounts:logout' %}">
                  <button type="submit"
                    class="w-full rounded-lg px-4 py-2 [text-align:_inherit] text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200">
                    Cerrar sesión
                  </button>
                </form>
              </li>
            </ul>
          </details>
        </li>
      </ul>
      
      <img class="w-16" src="https://images.builderservices.io/s/cdn/v1.0/i/m?url=https%3A%2F%2Fstorage.googleapis.com%2Fproduction-hostgator-chile-v1-0-3%2F573%2F1237573%2FEeoJHNah%2Fd473ee41415e43fc99acf1131253fde3&methods=resize%2C60%2C5000"/>
    </aside>

    <main class="flex-1 flex flex-col p-6">
      {% block content %}{% endblock %}
    </main>
  </div>
</body>

</html>

alenkura/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>Login</title>
</head>

<body>
    <main>
        <div class="flex flex-col items-center justify-center h-screen dark:bg-gray-900">
            <h1 class="text-3xl mb-4 font-bold dark:text-white">Bienvenido a Alenkura</h1>
            <form class="flex flex-col rounded-lg p-10 content-center shadow-xl dark:bg-gray-800 border border-gray-300 dark:border-gray-600" method="post">
                {% csrf_token %}
                <div class="mb-4">
                    <label for="user">
                        <span class="text-sm font-medium text-gray-700 dark:text-gray-200"> Usuario </span>
                
                        <input type="user" id="user" name="user"
                            class="p-2 mt-0.5 w-full rounded-lg border border-gray-300 shadow-md sm:text-sm dark:border-gray-600 dark:bg-gray-900 dark:text-white">
                    </label>
                    <label for="password">
                        <span class="text-sm font-medium text-gray-700 dark:text-gray-200"> Contraseña </span>
                
                        <input type="password" id="password" name="password"
                            class="p-2 mt-0.5 w-full rounded-lg border border-gray-300 shadow-md sm:text-sm dark:border-gray-600 dark:bg-gray-900 dark:text-white">
                    </label>
                </div>
                

                <button class="inline-block rounded-lg bg-indigo-600 px-12 py-3 text-white hover:bg-indigo-700 cursor-pointer"
                    type="submit">Iniciar sesión</button>
            </form>
        </div>
    </main>
</body>

</html>